### ISSUE TITLE
xf86-video-armsoc-rockchip not showing mouse pointer

### ISSUE THREAD

**Issue by teacupx** [rockchip-linux/xserver#6]
Hello. I noticed in the repo another video driver, different from glamor, named "xf86-video-armsoc-rockchip". It seems to work very well, actually it looks faster thatn glamor. The only problem is that mouse pointer disappears, and no option you set in conf file (swcursor true, hwcursor false, etc.) seems to have any effect to make pointer show.

I am using a Tinkerboard, so the issue is with the RK3288 SoC.

I noticed there is a specific repo for the xf86-video-armsoc-rockchip, but it has no issue tracker

**Comment by wzyy2** [comment]
Which SoC do you use?

**Comment by teacupx** [comment]
Sorry, I edited the original post with that info  and maybe you missed it. It's a Tinkerboard, with RK3288.

**Comment by wzyy2** [comment]
It shouldn't disappears. I just test them in rk3288 and hwcursor work well...

**Comment by teacupx** [comment]
Well, I built a Debian stretch image from the Rockchip repo in 2018/01/04, and I tested the armsoc driver by renaming:

- /etc/X11/20-armsoc.conf.bak to  20-armsoc.conf
- /etc/X11/20-modesetting.conf to 20-modesetting.conf.bak

With that setup, cursor is invisible. Is there anything different I should do to test it?

**Comment by teacupx** [comment]
Sorry, my fault, files are located at /etc/X11/xorg.conf.d/20-armsoc.conf

**Comment by wzyy2** [comment]
Can you upgrade your kernel to the latest release-4.4?

**Comment by teacupx** [comment]
Well, I built a whole new image, and here are the results:

- Mouse cursor still is invisible when hardware acceleration is enabled
- But now you can set in /etc/X11/xorg.conf.d/20-armsoc.conf the option "SWcursor"
- When you set "SWcursor" to "true", then you can see the pointer. However, it blinks sometimes, when you hover it over certain windows (Chromium, for example)

So it looks like the commit you made yesterday is a good workaround.

**Comment by teacupx** [comment]
I also did some performance tests, and here are the results:

GLAMOR:
- Requires special X server, which breaks compatibility with compositing window managers (compton, xfwm4, marco, etc.)
- Works fine with accelerated Chromium browser.
- Windowed glmark-es2 score: 31 fps average (higher is better)
- Maximized windows gtkperf tests score: 355.02 seconds (lower is better)

ARMSOC:
- Works with standard X server, and therefore is compatible with compositing window managers 
- Has some problem accelerated Chromium browser (glitches, cannot play full screen video, etc.)
- Windowed glmark-es2 score: 65 fps average
- Maximized windows gtkperf tests score: 17.38 seconds

So it seems like armsoc has a big performance advantage over glamor, particularly for GTK performance. Still, it seems less usable, because of the mouse pointer issues and glitches in Chromium. On the other hand, glamor special X server breaks compositing window managers, and that is a problem when you want to use any other DE than LXDE (even if it is just XFCE or MATE), because they use compositing WM.

**Comment by teacupx** [comment]
I am attaching the full results of the performace tests. They also include results for glamor with vsync disabled, and modesetting with glamor disabled ("Accelmethod" "none")
[performance_tests.zip](https://github.com/rockchip-linux/xserver/files/1639614/performance_tests.zip)

**Comment by wzyy2** [comment]
`Requires special X server, which breaks compatibility with compositing window managers `
I don't think window compositer might affect performance, you can disable it when using xfce\mate ..... 

`Windowed glmark-es2 score: 31 fps average (higher is better)`
No, windowed glmark-es2 score in glamor won't be less than vsync, it shouldn't be 31fps.
We have optimize GLES  performance for glamor-modesetting, it have best performance in theory.
If it's a windowed GLES program, GPU will render content to window buffer and CPU copy window buffer once to front buffer(Actually in modern display server, like wayland, 
It's GPU to copy window buffer to front buffer, that's why we say X11 have bad performance)
If it's a fullscreen GLES program, GPU will render content to window buffer and window buffer will be displayed directly.

I didn't study much about armsoc DDX, it might have same behavior, 
`Windowed glmark-es2 score: 65 fps average`
I didn't test armsoc with standard X server, but i have try it with our custom Xserver, and it only get 30~40 fps. Could you try it with custom Xserver?

`Maximized windows gtkperf tests score: 355.02 seconds`
Yep, glamor affect gtk performance, but i think it's accepted.
1. I don't feel much lag when using gtk app in glamor.
2. glamor can accell window draging.
3. If people care about UI performance for their app, they should use EGL+GLES, like GPU-Enabled Chromium and GLES-enabled QT-QML app.(but unfortunately, debian pakcage usually don't enable GLES feature).
`Requires special X server, which breaks compatibility with compositing window managers `
I don't think window compositer might affect performance, you can disable it when using xfce\mate ..... 

`Windowed glmark-es2 score: 31 fps average (higher is better)`
No, windowed glmark-es2 score in glamor won't be less than vsync, it shouldn't be 31fps.
We have optimize GLES  performance for glamor-modesetting, it have best performance in theory.
If it's a windowed GLES program, GPU will render content to window buffer and CPU copy window buffer once to front buffer(Actually in modern display server, like wayland, 
It's GPU to copy window buffer to front buffer, that's why we say X11 have bad performance)
If it's a fullscreen GLES program, GPU will render content to window buffer and window buffer will be displayed directly.

I didn't study much about armsoc DDX, it might have same behavior, 
`Windowed glmark-es2 score: 65 fps average`
I didn't test armsoc with standard X server, but i have try it with our custom Xserver, and it only get 30~40 fps. Could you try it with custom Xserver?

`Maximized windows gtkperf tests score: 355.02 seconds`
Yep, glamor affect gtk performance, but i think it's accepted.
1. I don't feel much lag when using gtk app in glamor.
2. glamor can accell window draging.
3. EGL-GLES apps have best performance with glamor, it's more userful than gtk. GPU-Enabled Chromium and GLES-enabled QT-QML app are typical EGL-GLES apps.
(Though unfortunately, most debian pakcages should be rebuild to enable GLES feature, since debian developers usually just simply apply X86 rules for arm packages).

"mouse pointer issues"
Try rebuild it with this commit reverted, but i don't have mouse pointer issues with the origin one.
https://github.com/rockchip-linux/xf86-video-armsoc/commit/67d4cffe67737458716116498a67546291def000

"mouse pointer issues"
Try rebuild it with this commit reverted, but i don't have mouse pointer issues with the origin one.
https://github.com/rockchip-linux/xf86-video-armsoc/commit/67d4cffe67737458716116498a67546291def000

**Comment by teacupx** [comment]
> No, windowed glmark-es2 score in glamor won't be less than vsync, it shouldn't be 31fps.
Well, I got way better performace by disbling VSync, although I saw some flickering in the videos in Youtube. There is more people recommending to disable VSyinc if you wnat better windowed GLES performance: https://tinkerboarding.co.uk/forum/thread-939-post-4117.html#pid4117

> I didn't test armsoc with standard X server, but i have try it with our custom Xserver, and it only get 30~40 fps. Could you try it with custom Xserver?
All the tests were done with the custom Xserver. I only installed the standard Xserver later, to test windows compositing.

> EGL-GLES apps have best performance with glamor, it's more userful than gtk.
I agree, not many people will use a Rockchip-based computer for desktop, most people will use it for videos or 3D apps

**Comment by fczuardi** [comment]
This also happens on the RK3328 of the Rock64 board, xserver-xorg-video-armsoc/bionic 1.9.3ayufan5 arm64 
I am also trying to use the computer as a desktop :)

**Comment by teacupx** [comment]
You may want to try with this package. It is the version you can find in this repo, but wih a small change reverting the part of the commit referenced two posts above that causes the trouble (not the whole commit, which also has some other useful features). 
[xserver-xorg-video-armsoc_1.9.3-ubuntu_armhf.deb.zip](https://github.com/rockchip-linux/xserver/files/1822624/xserver-xorg-video-armsoc_1.9.3-ubuntu_armhf.deb.zip)

**Comment by fczuardi** [comment]
Did the small change mentioned above got merged into the master branch? @wzyy2

**Comment by pronvit** [comment]
@wzyy2 `No, windowed glmark-es2 score in glamor won't be less than vsync, it shouldn't be 31fps.`

I'm definitely getting 30fps max with my es2 app in windowed mode. While in fullscreen mode or with DRM + GBM + EGL I get 60fps. I saw a mention somewhere that only performance of gl contexts with certain configuration degrades. But still, I don't quite understand why you're saying "EGL-GLES apps have best performance with glamor".

**Comment by digitalsanity** [comment]
@pronvit Did you try forcing CPU performance governor?  Maybe the default interactive governor is not tuned for more efficient use of resources..

**Comment by pronvit** [comment]
@digitalsanity I later discovered that using a fullscreen window helps to get 60 FPS as well, and I think @wzyy2 mentioned this somewhere (to use fullscreen windows for max performance). So I understand it's a rockchip's xserver & libmali bug/limitation at the moment.

**Comment by digitalsanity** [comment]
Also, it seems the only way to currently use glmark2-es2 to benchmark is to run it multiple times and compare the fps with 5-20 sessions running.  Wayland you can run 20x glmark2-es2 sessions simultaneously and you have good window/GUI responsiveness.  In X11 with any GLES enabled, you can run only 5x glmark2-es2 sessions at the same fps as Wayland, but the GUI responsiveness is awful.  This lags/blocks the apps and the GUI responsiveness falls apart.

Another good test is to open a terminal like lxterminal and do a: time find /usr/lib -- you will see how the scrolling chunks a page at a time.  With modeset driver and glamor disabled, you will see 0.7s or less vs 7s with glamor/armsoc enabled.
